# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180121_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='time_uloaded',
            new_name='time_taken',
        ),
    ]
